### ISSUE TITLE
Lab 2 - Section 2 Apicast: Plain - dead link encountered

### ISSUE THREAD

**Issue by honghuac** [redhat-gpe/rhte_lab_04_api_mgmt_and_service_mesh#26]
The deadlink "dvsdc" appears at the end of this statement in Lab 2 **The management of this API gateway occurs via a Kubernetes deployment as opposed to an OCP deploymentconfig. The reason for this is discussed previously in the section:** [_**dvsdc**_].

**Comment by jbride** [comment]
done
