### ISSUE TITLE
01_1_setup_Lab:  Step 5.2 - Update VM memory details and CPU details

### ISSUE THREAD

**Issue by darbyredhat** [redhat-gpe/rhte_lab_04_api_mgmt_and_service_mesh#34]
In Step 5.2

The NA RHTE VMs have more memory than specified in the lab instructions. 
The lab instructions refer to 16GB ... however the VMs actually have 32GB

```
$ cat /proc/meminfo | grep MemTotal
MemTotal:       32779928 kB
```
same applies for CPU.  Instructions refer to 4 CPUs ... but actual CPUs are 8

```
$ cat /proc/cpuinfo | awk '/^processor/{print $3}' | wc -l
8
```

**Comment by jbride** [comment]
fixed several months back
