### ISSUE TITLE
[Lab2] Curl command might needs to be updated

### ISSUE THREAD

**Issue by d-jana** [redhat-gpe/rhte_lab_04_api_mgmt_and_service_mesh#35]
In "[Lab2](https://jenkins.opentlc.com/jenkins/view/RHTE/job/rhte_lab_04_api_mgmt_and_service_mesh/lastSuccessfulBuild/artifact/tempMultiSCOFiles/01_api_mgmt_service_mesh/01_2_api_mgmt_service_mesh_Lab.html) > 2.2.6. Test Catalog Business Service > 2. From the terminal, execute the following:", curl command is not working.
Error is showing like below:
```
[djana-redhat.com@clientvm 1 ~]$ curl -v -k `echo "https://"$(oc get route/catalog-prod-apicast-$OCP_USERNAME -o template --template {{.spec.host}})"/products?user_key=$CATALOG_USER_KEY"`
Error from server (NotFound): routes.route.openshift.io "catalog-prod-apicast-developer" not found
* Could not resolve host: https; Unknown error
* Closing connection 0
curl: (6) Could not resolve host: https; Unknown error
```

It just missed "-n $GW_PROJECT" parameter. It works with below command:
```
curl -v -k `echo "https://"$(oc get route/catalog-prod-apicast-$OCP_USERNAME -n $GW_PROJECT -o template --template {{.spec.host}})"/products?user_key=$CATALOG_USER_KEY"`
```
or
```
curl -v -k `echo "https://"$(oc get route catalog-prod-apicast-$OCP_USERNAME -n $GW_PROJECT --template {{.spec.host}})"/products?user_key=$CATALOG_USER_KEY"`
```

Console log:
[CurlErrorAPICast.txt](https://github.com/redhat-gpe/rhte_lab_04_api_mgmt_and_service_mesh/files/2530997/CurlErrorAPICast.txt)

Can you please check once?

**Comment by jbride** [comment]
fixed several months ago.
