### ISSUE TITLE
[Environment Setup Lab] CF entry missing in OPENTLC

### ISSUE THREAD

**Issue by d-jana** [redhat-gpe/rhte_lab_04_api_mgmt_and_service_mesh#36]
In "[Environment Setup Lab](https://jenkins.opentlc.com/jenkins/view/RHTE/job/rhte_lab_04_api_mgmt_and_service_mesh/lastSuccessfulBuild/artifact/tempMultiSCOFiles/01_api_mgmt_service_mesh/01_1_setup_Lab.html) > 2.1.2. Access VM via OPENTLC or RHSE", "3scale API Mgmt & Service Mesh" should be present in CF as per instruction:
<img width="1324" alt="screenshot 2018-10-31 at 12 04 06 am" src="https://user-images.githubusercontent.com/34668540/47741611-aff8db00-dca0-11e8-891c-226e1b14155e.png">

I could not found that in OPENTLC:
<img width="1323" alt="screenshot 2018-10-31 at 12 03 50 am" src="https://user-images.githubusercontent.com/34668540/47741646-c868f580-dca0-11e8-9235-a57e674f2849.png">

Where as it is present in https://rhpds.redhat.com. I tested lab using https://rhpds.redhat.com.

Can you please check if you are able to see CF entry for "3scale API Mgmt & Service Mesh" in OPENTLC?

**Comment by jbride** [comment]
cloud forms entry for RHSE / OPEN courses was added a few months back
