### ISSUE TITLE
[Access VM via GUID Grabber] Step's text and screenshot are inconsistent

### ISSUE THREAD

**Issue by rdickens-redhat** [redhat-gpe/rhte_lab_04_api_mgmt_and_service_mesh#37]
"Access VM via GUID Grabber", step 7 instructs the reader to click "Reset Workstation", but the accompanying screenshot shows the button is labelled "RESET STATION".

Please confirm which label is correct.

**Comment by rdickens-redhat** [comment]
Link to "Access VM via GUID Grabber":

https://github.com/redhat-gpe/rhte_lab_04_api_mgmt_and_service_mesh/blob/master/modules/01_api_mgmt_service_mesh/01_1_setup_Lab.adoc#213-access-vm-via-guid-grabber

**Comment by jbride** [comment]
this has been fixed in a previous commit
