### ISSUE TITLE
[Confirmation Emails and SSH access] Headings are not appearing as per standard AsciiDoc styling

### ISSUE THREAD

**Issue by rdickens-redhat** [redhat-gpe/rhte_lab_04_api_mgmt_and_service_mesh#38]
In this [1] section I changed numbered steps into paragraphs, and added two headings using the AsciiDoc syntax: ".Heading". Although this is styled correctly in my editor, it doesn't appear styled correctly in GitHub.

Question: Is this an issue that should be resolved, or will the styling look OK in the built version?

[1] https://github.com/redhat-gpe/rhte_lab_04_api_mgmt_and_service_mesh/blob/master/modules/01_api_mgmt_service_mesh/01_1_setup_Lab.adoc#22-confirmation-emails-and-ssh-access

**Comment by rdickens-redhat** [comment]
Midyne,

Thanks for your feedback. I don't understand your suggestion of manually applying bold to the subheading. Your example is ".Heading", which is the content as it is now, which is failing to show as I expect.

**Comment by midspear** [comment]
@rdickens-redhat - Looks like GitHub removed the syntax I was trying to show you. You can enclose the text with asterisks to manually apply bold to those subheads. Put the 1st asterisk between the period and the text and the 2nd at the end of the text.

**Comment by rdickens-redhat** [comment]
@midspear 	Thank you. As you suggested, I have applied bold styling to the headings, which achieves my original goal. With that resolved I will close this issue.
