### ISSUE TITLE
Can we remove the "Alternatives" section from "API Mgmt and SM Lab?"

### ISSUE THREAD

**Issue by rdickens-redhat** [redhat-gpe/rhte_lab_04_api_mgmt_and_service_mesh#39]
Is the "Alternatives" section necessary? If not, I suggest it is deleted.

I understand the benefit to this information, but I don't think it adds value to this lab. The introduction to this paragraph states "...the following are related community initiatives that are not covered in this lab." My reason for suggesting this be deleted from the lab is that presenting information which is not directly relevant to the lab may obscure the information that *is* relevant.

[1] https://github.com/redhat-gpe/rhte_lab_04_api_mgmt_and_service_mesh/blob/master/modules/01_api_mgmt_service_mesh/01_2_api_mgmt_service_mesh_Lab.adoc#alternatives

**Comment by jbride** [comment]
Yes, the content found in that section is based on numerous questions asked by  students who conducted this lab in previous instructor led trainings.
