### ISSUE TITLE
Can the "Reference" section in the API Mgmt and SM lab be moved?

### ISSUE THREAD

**Issue by rdickens-redhat** [redhat-gpe/rhte_lab_04_api_mgmt_and_service_mesh#40]
Can we move the "Reference" section [1] to the Appendix? In its current location it provides little value to a student. References are generally a list of sources used to write the content. I doubt it is necessary for a student to have read the referenced material.

[1] https://github.com/redhat-gpe/rhte_lab_04_api_mgmt_and_service_mesh/blob/master/modules/01_api_mgmt_service_mesh/01_2_api_mgmt_service_mesh_Lab.adoc#12-reference

**Comment by rdickens-redhat** [comment]
I think the suggested reading is a valuable resource for students who are seeking more information. I recommend it be moved to an appendix, and mention of it be added to the Overview. Regardless of whether or not it moves, I think we need to add a brief description of this section's content.

**Comment by jbride** [comment]
done
